# 使用官方Java运行时作为父镜像
FROM openjdk:8-jre-alpine

# 将JAR文件复制到容器内
COPY ./user-center-0.0.1-SNAPSHOT.jar /app/

# 设置工作目录
WORKDIR /app

# 暴露端口 根据实际端口调整
EXPOSE 8080

# 启动应用
CMD ["java", "-jar", "user-center-0.0.1-SNAPSHOT.jar"]