version: '3'
services:
  friends-fronted:
    build:
      context: .
      dockerfile: Dockerfile-fronted
    ports:
      - "80:80" # 将容器的80端口映射到主机的80端口
    depends_on:
      - friends-backend # 确保后端服务先启动
    volumes:
      - /mysoft/nginx/conf:/etc/nginx/conf.d # 挂载nginx配置文件
  friends-backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    ports:
      - "8080:8080" # 将容器的8201端口映射到主机的8201端口